- name: Installation de Docker
  hosts: all
  become: true

  tasks:
    - name: Mise à jour du cache apt
      apt:
        update_cache: yes

    - name: Installation de Docker
      apt:
        name: docker.io
        state: present
